services:
  nodejs-server:
    image: nehaachopra/hello-world
    deploy:
      replicas: 5
    networks: 
      - hello-world-internal
  caddy:
    image: caddy:latest
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    networks:
      - hello-world-internal
    ports:
      - "80:80"
      - "443:443"

networks:
  hello-world-internal:
    driver: bridge
